### ISSUE TITLE
Spell power coefficient

### ISSUE THREAD

**Issue by Veeruli** [projectblitz/tracker#3]
The spell power coefficient scaling formulas are erroneous. For example, a r1 Holy Nova which has a base healing of 52 to 61 was healing me for nearly 600 in a PvP gear setup. With the 14,29% spell power coefficient which instant aoe spells are supposed to have, the cast would've required way more than the feasible bonus healing.

The exact formulas are as follows,

**Standard Spells:**

> (Cast Time of Spell) / 3.5 =  Benefit 
> 3.5  sec = 100%
> 3.0  sec = 85.71%
> 2.5  sec = 71.43%
> 2.0  sec = 57.14%
> 1.5  sec = 42.86%
> Instant  = 42.86%

**Over Time Spells:**

> (Duration of Spell / 15) =  Benefit 
> 3  sec = 20%
> 6  sec = 40%
> 9  sec = 60%
> 12  sec = 80%
> 15  sec and longer = 100%

**Standard and Over Time Spells:**
(abilities such as Immolate)

> (Duration / 15) / ((Duration / 15) + (Cast Time of Spell / 3.5)) = Portion to Over Time 
> 1 - Portion to Over Time = Portion to Standard 
> (Cast Time of Spell / 3.5) * Portion to Standard = Benefit Regular part of the spell 
> (Duration / 15) * Portion to Over Time = Benefit Over Time part of the spell

**Channeled Spells:**

> Cast Time of Spell / 3.5 =  Benefit 

**Area of Effect Spells:**

> (Cast Time of Spell / 3.5) / 3 =  Benefit 
> 10   sec = 95.24%
> 3.5  sec = 33.33%
> 3.0  sec = 28.57%
> 2.5  sec = 23.81%
> 2.0  sec = 19.05%
> 1.5  sec = 14.29%
> Instant  = 14.29%

[Source](https://wow.gamepedia.com/index.php?title=Spell_power&oldid=354556#Complete_Rework_in_the_Burning_Crusade)

**Comment by warlorddrak** [comment]
Could reproduce!

HN damage scales 16.06% and healing 30.35% across all ranks.

Both should be reduced to 14.29% scaling?

I also noticed Flash Heal scaling with 61.77%, which is off according to the formula. I will not change this yet, because I assume lots of other spells' scaling is off as well. Prob. fixing this on a by-report basis.

**Comment by warlorddrak** [comment]
Fixed!

**Comment by Veeruli** [comment]
Heal scaling seems to be erroneous with the new core as well, although to a lesser extent.
