### ISSUE TITLE
Mind Control (mechanic)

### ISSUE THREAD

**Issue by Veeruli** [projectblitz/tracker#5]
**Current issues:**
- Both priest Mind Control and Gnomish Mind Control Cap seem to have an unnaturally high chance of doing nothing. There is no resist or immune in the combat log, the spell simply instantly casts and cancels in the combat log (you gain mind control > mind control fades from you).
- Movement seems to break Mind Control. You can test it on by fearing a target and then mind controlling them.
- Players affected by Gnomish Mind Control Cap are automatically on stay, do not use any abilities and do not respond to any commands. (petfollow/petattack) There is no pet bar after using the gadget, either.

**Comment by warlorddrak** [comment]
Similar to #7 probably, marking it as `won't fix` for now.

**Comment by gianclaudio-giordano** [comment]
Just to add more informations:

Direct Mind control (from priest) to PLAYERS shows up the extra action bar (similiar to pet one) but it's empty. However the MCd player can autoattack with right click and stopattack with Esc or target removal

Direct Mind control to NPC show the correct extra bar with the NPC abilities (if they have some). Tried with scarlet priests with Renew, Smite, etc.

Mind Control from gnomish cap to PLAYERS actually charms the target but the target will just stand still, or keep running headlessly if used to a running target. Doesn't follow, doesn't attack. No extra bar pops up, so you can't really set defensive, passive, aggressive etc.

Mind control from gnomish cap to NPC works perfectly, the NPC will follow, extra bar pops up and can use their abilities flawlessly.

**Comment by Veeruli** [comment]
Fixed on the new core.
