### ISSUE TITLE
Visual position of crowd controlled targets

### ISSUE THREAD

**Issue by Veeruli** [projectblitz/tracker#7]
It seems that visual placement of crowd controlled players doesn't get updated during the crowd control, but only afterwards once the player takes an action or moves so that their position gets updated on the server. This is a potential cause for the common visual bug which effects most crowd control abilities like Scatter Shot, Blind, Fear, etc. and causes the caster unable to see the exact position of their crowd controlled target.

**Comment by warlorddrak** [comment]
This will probably be pretty hard to fix and has been broken on mangos for a long time.
I will thus most likely rather focus on other issues.

**Comment by Veeruli** [comment]
Seems fixed on the new core, but you might need to conduct further testing.
